version: '3.8'

services:
  exam-converter:
    build: .
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./public/python:/usr/share/nginx/html/python:ro
    restart: unless-stopped

  # Optional: Add a development service
  exam-converter-dev:
    build:
      context: .
      target: frontend-builder
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
    profiles:
      - dev